# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

pod 'FMDB'
pod 'AFNetworking'

# Avoid adding libPods to the "Link Binary with Libraries" phase
# http://stackoverflow.com/questions/17092822/building-a-static-library-with-cocoapods
link_with ['InboxTests']

target "InboxTests", :exclusive => true do
	pod 'Kiwi/XCTest'
end

